"""Add player stats, workout history, and preferences tables

Revision ID: 5372338d8fcb
Revises: a4decc921d21
Create Date: 2025-11-15 14:24:29.803154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5372338d8fcb'
down_revision: Union[str, Sequence[str], None] = 'a4decc921d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerpreferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('match_notifications', sa.Boolean(), nullable=False),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(), nullable=False),
    sa.Column('show_stats', sa.Boolean(), nullable=False),
    sa.Column('show_workout_history', sa.Boolean(), nullable=False),
    sa.Column('preferred_exercises', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('auto_match', sa.Boolean(), nullable=False),
    sa.Column('default_workout_duration', sa.Integer(), nullable=False),
    sa.Column('rest_time_between_exercises', sa.Integer(), nullable=False),
    sa.Column('enable_cv_detection', sa.Boolean(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerpreferences_user_id'), 'playerpreferences', ['user_id'], unique=True)
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.Column('games_tied', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_workout_time', sa.Integer(), nullable=False),
    sa.Column('best_pushups', sa.Integer(), nullable=False),
    sa.Column('best_squats', sa.Integer(), nullable=False),
    sa.Column('best_pullups', sa.Integer(), nullable=False),
    sa.Column('best_burpees', sa.Integer(), nullable=False),
    sa.Column('best_plank_time', sa.Integer(), nullable=False),
    sa.Column('best_wall_sit_time', sa.Integer(), nullable=False),
    sa.Column('current_win_streak', sa.Integer(), nullable=False),
    sa.Column('longest_win_streak', sa.Integer(), nullable=False),
    sa.Column('current_workout_streak', sa.Integer(), nullable=False),
    sa.Column('longest_workout_streak', sa.Integer(), nullable=False),
    sa.Column('last_workout_at', sa.DateTime(), nullable=True),
    sa.Column('last_game_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstats_user_id'), 'playerstats', ['user_id'], unique=True)
    op.create_table('playerworkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('exercise_category', sa.String(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('form_rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['game_session_id'], ['gamesession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerworkout_user_id'), 'playerworkout', ['user_id'], unique=False)
    op.add_column('user', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('user', sa.Column('experience_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('user', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'last_seen_at')
    op.drop_column('user', 'is_online')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'experience_points')
    op.drop_column('user', 'level')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'display_name')
    op.drop_index(op.f('ix_playerworkout_user_id'), table_name='playerworkout')
    op.drop_table('playerworkout')
    op.drop_index(op.f('ix_playerstats_user_id'), table_name='playerstats')
    op.drop_table('playerstats')
    op.drop_index(op.f('ix_playerpreferences_user_id'), table_name='playerpreferences')
    op.drop_table('playerpreferences')
    # ### end Alembic commands ###
